/**
 * convert_krdict.js
 * Node.js script — đọc các file JSON KRDict trong Dict Json/, 
 * trích xuất từ + tất cả nghĩa Việt + định nghĩa + POS + ví dụ,
 * xuất ra public/assets/js/vocab-dictionary-full.js
 *
 * Usage: node convert_krdict.js
 */

const fs = require('fs');
const path = require('path');

const INPUT_DIR = path.join(__dirname, 'Dict Json');
const OUTPUT_FILE = path.join(__dirname, 'public', 'assets', 'js', 'vocab-dictionary-full.js');

function featList(obj) {
    if (!obj) return [];
    return Array.isArray(obj) ? obj : [obj];
}

function getFeatVal(feats, att) {
    const f = feats.find(x => x.att === att);
    return f ? f.val : '';
}

function clean(text) {
    return text.replace(/\s+/g, ' ').trim();
}

const files = fs.readdirSync(INPUT_DIR)
    .filter(f => f.endsWith('.json'))
    .sort();

const allEntries = [];
const seenWords = new Set();

for (const file of files) {
    const raw = fs.readFileSync(path.join(INPUT_DIR, file), 'utf8');
    const data = JSON.parse(raw);
    const lexicalEntries = data?.LexicalResource?.Lexicon?.LexicalEntry;
    if (!lexicalEntries) continue;

    for (const entry of lexicalEntries) {
        const baseWord = entry?.Lemma?.feat?.val;
        if (!baseWord) continue;

        const entryFeats = featList(entry.feat);
        const pos = getFeatVal(entryFeats, 'partOfSpeech') || '';

        const senses = featList(entry.Sense);
        const sensePairs = [];  // [{m, d, x: []}]
        let koDef = '';

        for (const sense of senses) {
            const senseFeats = featList(sense.feat);
            const kd = getFeatVal(senseFeats, 'definition');
            if (kd && !koDef) koDef = clean(kd);

            // Vietnamese meanings
            const eqs = featList(sense.Equivalent);
            let viLemma = '', viDef = '';
            for (const eq of eqs) {
                const fs2 = featList(eq.feat);
                const lang = getFeatVal(fs2, 'language');
                if (lang === '베트남어') {
                    viLemma = clean(getFeatVal(fs2, 'lemma')) || viLemma;
                    viDef = clean(getFeatVal(fs2, 'definition')) || viDef;
                }
            }

            // Examples for THIS sense
            const senseExamples = [];
            const exs = featList(sense.SenseExample);
            for (const ex of exs) {
                const exFeats = featList(ex.feat);
                const type = getFeatVal(exFeats, 'type');
                const example = getFeatVal(exFeats, 'example');
                if (example && type === '문장' && !senseExamples.includes(example)) {
                    senseExamples.push(example);
                }
            }

            if (viLemma) {
                if (!sensePairs.some(sp => sp.m === viLemma)) {
                    const sp = { m: viLemma };
                    if (viDef) sp.d = viDef;
                    if (senseExamples.length > 0) sp.x = senseExamples.slice(0, 2);
                    sensePairs.push(sp);
                }
            }
        }

        if (sensePairs.length === 0) continue;
        if (seenWords.has(baseWord)) continue;
        seenWords.add(baseWord);

        const compact = { w: baseWord };
        if (sensePairs.length === 1) {
            compact.m = sensePairs[0].m;
            if (sensePairs[0].d) compact.d = sensePairs[0].d;
            if (sensePairs[0].x) compact.x = sensePairs[0].x;
        } else {
            compact.s = sensePairs.slice(0, 5);
            compact.m = sensePairs.map(sp => sp.m).join('; ');
        }
        if (koDef) compact.k = koDef;
        if (pos) compact.t = pos;

        allEntries.push(compact);
    }
}

// Generate compact JS output
const json = JSON.stringify(allEntries);

const output = `// Auto-generated by convert_krdict.js — ${allEntries.length} entries
// Source: KRDict 한국어기초사전 (krdict.korean.go.kr)
// Generated: ${new Date().toISOString()}
window.AutoVocabDictFull = ${json};
window.dispatchEvent(new CustomEvent('fulldictready'));
`;

fs.writeFileSync(OUTPUT_FILE, output, 'utf8');

const outputSize = Buffer.byteLength(output, 'utf8');
console.log(`Converted ${files.length} files → ${allEntries.length} entries`);
console.log(`Output: ${OUTPUT_FILE}`);
console.log(`Size: ${(outputSize / 1024 / 1024).toFixed(2)} MB (raw), ~${(outputSize / 1024 / 1024 * 0.25).toFixed(2)} MB (est. gzipped)`);

// Stats
const withDef = allEntries.filter(e => e.d || (e.s && e.s.some(sp => sp.d))).length;
const withKo = allEntries.filter(e => e.k).length;
const multi = allEntries.filter(e => e.s).length;
console.log(`With VN definition: ${withDef}`);
console.log(`With KR definition: ${withKo}`);
console.log(`Multiple meanings: ${multi}`);
